services:
  - type: web
    name: kota-api
    runtime: docker
    rootDir: .
    dockerfilePath: apps/kota-api/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FAKESTORE_API_URL
        value: https://fakestoreapi.com